const ALL_PRODUCTS = [
  {
    id: 101892, emoji: "🛒", name: "Kolica Compact 75 l Villager", cat: "ostalo",
    price: 6000,
    img: "Kolica Villager Compact 75 l.png",
    desc: "Kolica (tačke) zapremine 75L za rad u dvorištu i polju.",
    fullDesc: "Kompaktna kolica VILLAGER zapremine 75 litara, pogodna za prevoz zemlje, đubriva, alata i drugih materijala.",
    activeSubstance: "—", dosage: "—", waiting: "—", crops: [],
    features: ["Zapremina 75 L", "Kompaktna konstrukcija", "Za dvorište i imanje"],
    season: "Sva godišnja doba",
    relatedIds: []
  },
  {
    id: 101893, emoji: "🛒", name: "Kolica Standard 85 l", cat: "ostalo",
    price: 5500,
    img: "Kolica Villager Standard 85 l.png",
    desc: "Standardna kolica (tačke) zapremine 85L.",
    fullDesc: "Standardna kolica zapremine 85 litara za prevoz materijala u dvorištu, voćnjaku i na njivi.",
    activeSubstance: "—", dosage: "—", waiting: "—", crops: [],
    features: ["Zapremina 85 L", "Praktična upotreba", "Za razne poslove"],
    season: "Sva godišnja doba",
    relatedIds: []
  },
  {
    id: 102678, emoji: "💧", name: "Potapajuća pumpa za prljavu vodu VSP 10000", cat: "ostalo",
    price: 8000,
    img: "POTAPAJUCA PUMPA ZA PRLJAVU VODU VSP 10000.png",
    desc: "Potapajuća pumpa za ispumpavanje prljave vode.",
    fullDesc: "Potapajuća pumpa VSP 10000 za ispumpavanje prljave vode iz šahti, podruma, rezervoara i sličnih mesta.",
    activeSubstance: "—", dosage: "—", waiting: "—", crops: [],
    features: ["Za prljavu vodu", "Potapajući rad", "Kućna i pomoćna upotreba"],
    season: "Sva godišnja doba",
    relatedIds: []
  },
  {
    id: 101507, emoji: "🌿", name: "Električna kosačica Villy 1400P", cat: "ostalo",
    price: 11250,
    img: "ELEKTRICNA KOSACICA VILLY 1400P.png",
    desc: "Električna kosačica za održavanje travnjaka.",
    fullDesc: "Električna kosačica VILLY 1400P za redovno košenje travnjaka oko kuće i vikendice.",
    activeSubstance: "—", dosage: "—", waiting: "—", crops: [],
    features: ["Električni pogon", "Za travnjake", "Jednostavno rukovanje"],
    season: "Proleće / Leto / Jesen",
    relatedIds: []
  },
  {
    id: 101505, emoji: "🌿", name: "Električna kosačica Villy 1200 P", cat: "ostalo",
    price: 8600,
    img: "ELEKTRICNA KOSACICA VILLY 1200 P.png",
    desc: "Električna kosačica za manje i srednje travnjake.",
    fullDesc: "Električna kosačica VILLY 1200 P namenjena je održavanju travnjaka u dvorištu.",
    activeSubstance: "—", dosage: "—", waiting: "—", crops: [],
    features: ["Električni pogon", "Lagana i praktična", "Lako održavanje"],
    season: "Proleće / Leto / Jesen",
    relatedIds: []
  },
  {
    id: 102277, emoji: "💦", name: "Motorna pumpa za vodu Villager WP 36P", cat: "ostalo",
    price: 30000,
    img: "MOTORNA PUMPA ZA VODU VILLAGER WP 36P.png",
    desc: "Motorna pumpa za prebacivanje vode i navodnjavanje.",
    fullDesc: "Motorna pumpa VILLAGER WP 36P pogodna za navodnjavanje, ispumpavanje i prebacivanje vode na imanju.",
    activeSubstance: "—", dosage: "—", waiting: "—", crops: [],
    features: ["Motorni pogon", "Terenski rad", "Za navodnjavanje/ispumpavanje"],
    season: "Proleće / Leto",
    relatedIds: []
  },
  {
    id: 103205, emoji: "🛢️", name: "Ulje za dvotaktne motore 100ml Villager", cat: "ostalo",
    price: 110,
    img: "ULJE ZA DVOTAKTNE MOTORE 100ML VILLAGER.png",
    desc: "Ulje za 2T motore, pakovanje 100 ml.",
    fullDesc: "Ulje za dvotaktne motore VILLAGER (100 ml) za pripremu mešavine goriva kod 2T uređaja.",
    activeSubstance: "—", dosage: "Po preporuci proizvođača uređaja", waiting: "—", crops: [],
    features: ["Za 2T motore", "Pakovanje 100 ml", "Za mešavinu goriva"],
    season: "Sva godišnja doba",
    relatedIds: []
  },
  {
    id: 1001393, emoji: "🛢️", name: "010-6361 - Ulje za dvotaktne motore - zeleno, 100 ml", cat: "ostalo",
    price: 110,
    img: "010-6361 - ULJE ZA DVOTAKTNE MOTORE - ZELENO, 100ML.png",
    desc: "Zeleno ulje za 2T motore, pakovanje 100 ml.",
    fullDesc: "Zeleno ulje za dvotaktne motore (100 ml) za pripremu mešavine goriva kod 2T uređaja.",
    activeSubstance: "—", dosage: "Po preporuci proizvođača uređaja", waiting: "—", crops: [],
    features: ["Za 2T motore", "Zeleno (lakša kontrola mešavine)", "Pakovanje 100 ml"],
    season: "Sva godišnja doba",
    relatedIds: []
  },
  {
    id: 116472, emoji: "🧴", name: "Mast višenamenska Vill 120 g", cat: "ostalo",
    price: 390,
    img: "MAST VISENAMENSKA VILL 120 GR.png",
    desc: "Višenamenska mast za podmazivanje, 120 g.",
    fullDesc: "Višenamenska mast (120 g) za podmazivanje i zaštitu pokretnih delova alata i mašina.",
    activeSubstance: "—", dosage: "Po potrebi", waiting: "—", crops: [],
    features: ["Pakovanje 120 g", "Višenamenska upotreba", "Smanjuje trenje i habanje"],
    season: "Sva godišnja doba",
    relatedIds: []
  },
  {
    id: 116909, emoji: "⛽", name: "Motorna kosacica Atlas 5001 T", cat: "ostalo",
    price: 26000,
    img: "Motorna kosacica Atlas 5001 T.png",
    desc: "Motorna kosačica za travnjake i okućnice.",
    fullDesc: "Motorna kosačica Atlas 5001 T za košenje travnjaka na većim površinama (dvorišta, voćnjaci, zelene površine).",
    activeSubstance: "—", dosage: "—", waiting: "—", crops: [],
    features: ["Motorni pogon", "Za veće površine", "Robusna konstrukcija"],
    season: "Proleće / Leto / Jesen",
    relatedIds: []
  },
  {
    id: 116908, emoji: "⛽", name: "Motorna kosacica Atlas 5001 B", cat: "ostalo",
    price: 32500,
    img: "Motorna kosacica Atlas 5001 B.png",
    desc: "Motorna kosačica za održavanje travnjaka.",
    fullDesc: "Motorna kosačica Atlas 5001 B pogodna za redovno košenje travnjaka i zelenih površina.",
    activeSubstance: "—", dosage: "—", waiting: "—", crops: [],
    features: ["Motorni pogon", "Efikasno košenje", "Za dvorišta i okućnice"],
    season: "Proleće / Leto / Jesen",
    relatedIds: []
  },
  {
    id: 118977, emoji: "🪚", name: "Ulje za lanac testerol 1l villager", cat: "ostalo",
    price: 320,
    img: "Ulje za lanac testerol 1l villager.png",
    desc: "Ulje za podmazivanje lanca testere, 1L.",
    fullDesc: "Ulje za lanac testere (Testerol) VILLAGER u pakovanju od 1 litra za podmazivanje lanca i vodilice.",
    activeSubstance: "—", dosage: "Po potrebi", waiting: "—", crops: [],
    features: ["Pakovanje 1 L", "Za lanac i vodilicu", "Smanjuje habanje"],
    season: "Sva godišnja doba",
    relatedIds: []
  },
  {
    id: 121024, emoji: "🪚", name: "Ulje za lanac testerol 3l villager", cat: "ostalo",
    price: 900,
    img: "ULJE ZA LANAC TESTEROL 3L.png",
    desc: "Ulje za lanac testere, 3L.",
    fullDesc: "Ulje za lanac testere (Testerol) u pakovanju od 3 litra za redovno podmazivanje lanca i vodilice.",
    activeSubstance: "—", dosage: "Po potrebi", waiting: "—", crops: [],
    features: ["Pakovanje 3 L", "Za lanac i vodilicu", "Za redovnu upotrebu"],
    season: "Sva godišnja doba",
    relatedIds: []
  },
  {
    id: 120994, emoji: "🪚", name: "Ulje za lanac 5l AGM", cat: "ostalo",
    price: 1450,
    img: "Ulje za lanac 5l AGM.png",
    desc: "Ulje za lanac testere, 5L (AGM).",
    fullDesc: "AGM ulje za lanac u pakovanju od 5 litara za podmazivanje lanca i vodilice motornih testera.",
    activeSubstance: "—", dosage: "Po potrebi", waiting: "—", crops: [],
    features: ["Pakovanje 5 L", "Za lanac i vodilicu", "Ekonomično pakovanje"],
    season: "Sva godišnja doba",
    relatedIds: []
  },
  {
    id: 120306, emoji: "🧪", name: "Prskalica Hortus 5 l", cat: "ostalo",
    price: 1450,
    img: "PRSKALICA HORTUS 5L.png",
    desc: "Ručna prskalica zapremine 5L.",
    fullDesc: "Ručna prskalica HORTUS 5L za tretmane u bašti, voćnjaku i oko kuće (zaštita bilja, prihrana i sl.).",
    activeSubstance: "—", dosage: "—", waiting: "—", crops: [],
    features: ["Zapremina 5 L", "Ručni rad", "Za baštu i voćnjak"],
    season: "Proleće / Leto",
    relatedIds: []
  },
  {
    id: 120307, emoji: "🧪", name: "Prskalica Hortus 8 l", cat: "ostalo",
    price: 1550,
    img: "PRSKALICA HORTUS 8L.png",
    desc: "Ručna prskalica zapremine 8L.",
    fullDesc: "Ručna prskalica HORTUS 8L pogodna za veće tretmane u bašti i voćnjaku.",
    activeSubstance: "—", dosage: "—", waiting: "—", crops: [],
    features: ["Zapremina 8 L", "Ručni rad", "Za veće površine"],
    season: "Proleće / Leto",
    relatedIds: []
  },
  {
    id: 120305, emoji: "🧪", name: "Prskalica Hortus 10 l", cat: "ostalo",
    price: 1650,
    img: "PRSKALICA HORTUS 10L.png",
    desc: "Ručna prskalica zapremine 10L.",
    fullDesc: "Ručna prskalica HORTUS 10L za tretmane zaštite i prihrane na većim površinama.",
    activeSubstance: "—", dosage: "—", waiting: "—", crops: [],
    features: ["Zapremina 10 L", "Ručni rad", "Praktična za duže tretmane"],
    season: "Proleće / Leto",
    relatedIds: []
  },
  {
    id: 121865, emoji: "🪚", name: "Ulje za lanac testerol 2l villager", cat: "ostalo",
    price: 650,
    img: "ULJE ZA LANAC TESTEROL 2L.png",
    desc: "Ulje za lanac testere, 2L.",
    fullDesc: "Ulje za lanac testere (Testerol) u pakovanju od 2 litra za podmazivanje lanca i vodilice.",
    activeSubstance: "—", dosage: "Po potrebi", waiting: "—", crops: [],
    features: ["Pakovanje 2 L", "Za lanac i vodilicu", "Za redovnu upotrebu"],
    season: "Sva godišnja doba",
    relatedIds: []
  },
];
