const ALL_PRODUCTS = [
  {
    id: 0, emoji: "🌿", name: "Herbicid Spring Pro", cat: "herbicid", badge: "Bestseler",
    desc: "Efikasna borba sa korovima u žitaricama.",
    fullDesc: "Spring Pro je selektivni sistemski herbicid namenjen suzbijanju jednogodišnjih i višegodišnjih uskolisnih i širokolisnih korova u ozimim i jarim žitaricama. Deluje brzo — vidljivi simptomi na korovima nakon 3–5 dana, potpuno odumiranje za 2–3 nedelje.",
    activeSubstance: "Florasulam 5% + 2,4-D 300 g/l",
    dosage: "0.6–0.8 l/ha",
    waiting: "35 dana",
    crops: ["Pšenica", "Ječam", "Ovas", "Raž"],
    features: ["Sistemska resorpcija kroz list i koren", "Efikasan na temperaturama od 5°C", "Ne zahteva kišnu barijeru", "Bezbedno za sledeće useve u rotaciji"],
    season: "Proleće / Jesen",
    relatedIds: [1, 2, 3]
  },
  {
    id: 1, emoji: "🌾", name: "Herbicid Tribunal", cat: "herbicid",
    desc: "Postemergentna zaštita ozime pšenice.",
    fullDesc: "Tribunal je kombinovani postemergentni herbicid za suzbijanje jednogodišnjih uskolisnih i širokolisnih korova u ozimoj pšenici i ječmu. Posebno efikasan na travnim korovima poput divljeg ovsa i mišjakinje.",
    activeSubstance: "Propoxycarbazone-sodium 70 g/kg",
    dosage: "0.5 kg/ha",
    waiting: "42 dana",
    crops: ["Ozima pšenica", "Ozimi ječam"],
    features: ["Selektivan za žitarice", "Upija se kroz list i koren", "Efikasan na hladnom vremenu", "Registrovan u Srbiji"],
    season: "Jesen / Zima",
    relatedIds: [0, 2, 6]
  },
  {
    id: 2, emoji: "🌽", name: "Atrazin 500 SC", cat: "herbicid",
    desc: "Selektivni herbicid za kukuruz.",
    fullDesc: "Atrazin 500 SC je rezidualni herbicid koji se primenjuje pre nicanja korova u usevima kukuruza. Formiran kao suspenzija koncentrata, pruža dugotrajnu zaštitu od većine jednogodišnjih korova.",
    activeSubstance: "Atrazin 500 g/l",
    dosage: "1.5–2.5 l/ha",
    waiting: "—",
    crops: ["Kukuruz"],
    features: ["Pre i post-emergentna primena", "Rezidualno dejstvo 6–8 nedelja", "Niska toksičnost za pčele", "Ekonomična primena"],
    season: "Proleće",
    relatedIds: [3, 8, 17]
  },
  {
    id: 3, emoji: "🌻", name: "Herbicid Select", cat: "herbicid",
    desc: "Suzbijanje uskolisnih korova.",
    fullDesc: "Select 120 EC je selektivni postemergentni herbicid za suzbijanje jednogodišnjih i višegodišnjih uskolisnih korova u usevima suncokreta, soje, šećerne repe i povrća. Odlično dejstvo na divlji ovas i pirevinu.",
    activeSubstance: "Clethodim 120 g/l",
    dosage: "0.4–0.8 l/ha",
    waiting: "28 dana",
    crops: ["Suncokret", "Soja", "Šećerna repa", "Uljana repica"],
    features: ["Sistemska resorpcija", "Vidljivi simptomi za 5–7 dana", "Može se mešati sa insekticidima", "Selektivan za širokolisne useve"],
    season: "Proleće / Leto",
    relatedIds: [0, 18, 19]
  },
  {
    id: 4, emoji: "🍄", name: "Fungicid Mancozeb", cat: "fungicid", badge: "Akcija",
    desc: "Kontaktni fungicid širokoga spektra.",
    fullDesc: "Mancozeb 80 WP je kontaktni fungicid i akaricid koji se koristi preventivno. Pruža zaštitu od čitavog spektra gljivičnih bolesti lista i plodova. Nezaobilazan u svim programima zaštite biljaka.",
    activeSubstance: "Mankozeb 80%",
    dosage: "2.0–2.5 kg/ha",
    waiting: "21 dan",
    crops: ["Krompir", "Paradajz", "Vinova loza", "Jabuka", "Paprika"],
    features: ["Preventivno dejstvo", "Širok spektar delovanja", "Kompatibilan sa većinom fungicida", "Povoljna cena"],
    season: "Proleće / Leto",
    relatedIds: [5, 6, 7]
  },
  {
    id: 5, emoji: "🔵", name: "Fungicid Amistar", cat: "fungicid",
    desc: "Sistemska zaštita suncokreta i kukuruza.",
    fullDesc: "Amistar 250 SC sadrži azoksistrobin iz klase strobilurina. Deluje preventivno, kurativno i eradikatički, pružajući dugotrajnu sistemsku zaštitu. Uz zaštitu poboljšava i vitalnost same biljke.",
    activeSubstance: "Azoxystrobin 250 g/l",
    dosage: "0.8–1.0 l/ha",
    waiting: "35 dana",
    crops: ["Kukuruz", "Suncokret", "Pšenica", "Ječam"],
    features: ["Sistemska resorpcija i translaminarno kretanje", "Trajanje zaštite 3–4 nedelje", "Poboljšava vitalnost biljke", "Može se primeniti helikopterom"],
    season: "Leto",
    relatedIds: [4, 6, 23]
  },
  {
    id: 6, emoji: "🌿", name: "Folicur EW 250", cat: "fungicid",
    desc: "Triazolni fungicid za žitarice.",
    fullDesc: "Folicur EW 250 sadrži tebukonazol iz grupe triazola i predstavlja jedan od standardnih fungicida za zaštitu ozimih i jarih žitarica od lisnih bolesti, rđe, pepelnice i fuzarioze klasa.",
    activeSubstance: "Tebukonazol 250 g/l",
    dosage: "1.0 l/ha",
    waiting: "35 dana",
    crops: ["Pšenica", "Ječam", "Raž", "Triticale"],
    features: ["Kurativno i preventivno dejstvo", "Odlična sistemska resorpcija", "Stabilno u toplim uslovima", "Registrovan za suzbijanje fuzarioza"],
    season: "Proleće / Jesen",
    relatedIds: [4, 5, 1]
  },
  {
    id: 7, emoji: "🍇", name: "Fungicid Ridomil", cat: "fungicid",
    desc: "Zaštita vinove loze od plamenjače.",
    fullDesc: "Ridomil Gold MZ je kombinovani fungicid koji sadrži metalaksil-M (sistemičan) i mankozeb (kontaktan). Pruža dvostruku zaštitu od plamenjače vinove loze i krompira, kako preventivno tako i kurativno.",
    activeSubstance: "Metalaksil-M 40 g/kg + Mankozeb 640 g/kg",
    dosage: "2.5 kg/ha",
    waiting: "28 dana",
    crops: ["Vinova loza", "Krompir", "Paradajz", "Luk"],
    features: ["Sistemska + kontaktna zaštita", "Efikasan u kišnom periodu", "Kurativno dejstvo do 3 dana posle zaraze", "Sprečava sporulaciju"],
    season: "Proleće / Leto",
    relatedIds: [4, 5, 9]
  },
  {
    id: 8, emoji: "🐛", name: "Insekticid Lambda", cat: "insekticid",
    desc: "Kontaktni piretroid za razne štetočine.",
    fullDesc: "Lambda-S 2.5 EC je insekticid iz grupe piretroida sa kontaktnim i digestivnim delovanjem. Efikasan na velikom broju štetnih insekata u žitaricama, povrću i voćnjacima. Brzo knock-down dejstvo.",
    activeSubstance: "Lambda-cihalotrin 2.5 g/l",
    dosage: "0.3–0.5 l/ha",
    waiting: "14 dana",
    crops: ["Pšenica", "Kukuruz", "Suncokret", "Krompir", "Jabuka"],
    features: ["Brzo knock-down dejstvo", "Kontaktno i digestivno delovanje", "Niska cena po tretmanu", "Ekonomična formulacija"],
    season: "Proleće / Leto",
    relatedIds: [9, 10, 11]
  },
  {
    id: 9, emoji: "🔴", name: "Akaricid Vertimec", cat: "insekticid",
    desc: "Suzbijanje pauka crvenih.",
    fullDesc: "Vertimec 018 EC sadrži abamektin, prirodni produkt fermentacije. Efikasan je akaricid i insekticid za suzbijanje grinja (pauka crvenih) i minera lista u voćnjacima i povrtnjacima.",
    activeSubstance: "Abamektin 18 g/l",
    dosage: "0.75–1.0 l/ha",
    waiting: "7 dana",
    crops: ["Jabuka", "Kruška", "Breskva", "Paradajz", "Krastavac"],
    features: ["Biološkog porekla", "Translaminarno kretanje", "Efikasan na svim stadijumima grinja", "Kratka karenca"],
    season: "Leto",
    relatedIds: [8, 10, 23]
  },
  {
    id: 10, emoji: "🐞", name: "Insekticid Regent", cat: "insekticid", badge: "Novo",
    desc: "Zaštita od žičnjaka i gusenica.",
    fullDesc: "Regent 800 WG sadrži fipronil i koristi se za dezinfekciju semena i zaštitu od zemljišnih i nadzemnih štetočina. Posebno efikasan protiv žičnjaka, sovici i lisnih vaši.",
    activeSubstance: "Fipronil 800 g/kg",
    dosage: "Tretman semena: 5–8 g/100 kg semena",
    waiting: "—",
    crops: ["Kukuruz", "Suncokret", "Šećerna repa", "Soja"],
    features: ["Sistemska resorpcija kroz koren", "Dugotrajno dejstvo iz semena", "Zaštita u ranoj fazi razvoja", "Kombinovano dejstvo"],
    season: "Proleće",
    relatedIds: [8, 11, 17]
  },
  {
    id: 11, emoji: "🦟", name: "Insekticid Actara", cat: "insekticid",
    desc: "Sistemski insekticid za lisne vaši.",
    fullDesc: "Actara 25 WG sadrži thiamethoxam iz grupe neonikotinoida. Sistemski insekticid koji se apsorbuje kroz koren i listove, pružajući dugotrajnu zaštitu od sisajućih i nekih glodajućih insekata.",
    activeSubstance: "Thiamethoxam 250 g/kg",
    dosage: "0.08–0.14 kg/ha",
    waiting: "21 dan",
    crops: ["Pšenica", "Krompir", "Paprika", "Paradajz", "Jabuka"],
    features: ["Sistemska i kontaktna aktivnost", "Trajanje zaštite do 4 nedelje", "Efikasan na rezistentnim populacijama vaši", "Pogodna WG formulacija"],
    season: "Proleće / Leto",
    relatedIds: [8, 9, 10]
  },
  {
    id: 12, emoji: "🌱", name: "NPK 15:15:15", cat: "djubrivo", badge: "Bestseler",
    desc: "Kompleksno mineralno đubrivo.",
    fullDesc: "NPK 15:15:15 je granulisano kompleksno mineralno đubrivo sa ujednačenim sadržajem azota, fosfora i kalijuma. Idealno za osnovnu i startnu primenu u svim usevima i zasadima.",
    activeSubstance: "N:P₂O₅:K₂O = 15:15:15",
    dosage: "300–500 kg/ha (osnovna gnojidba)",
    waiting: "—",
    crops: ["Sve ratarske kulture", "Povrće", "Voće", "Livade"],
    features: ["Ujednačen odnos makroelemenata", "Brzo se rastvara u zemljištu", "Moguće kombinovanje sa herbicidima", "Dostupno u vrećama 50 kg i rasuto"],
    season: "Jesen / Proleće",
    relatedIds: [13, 14, 15]
  },
  {
    id: 13, emoji: "💧", name: "Folijarna Ishrana", cat: "djubrivo",
    desc: "Prihrana mikroelementima kroz list.",
    fullDesc: "Poliksol Forte je tečno folijarno đubrivo obogaćeno azotom, borom, manganom, cinkom i gvožđem u helatnoj formi. Brzo se apsorbuje kroz list, idealno u uslovima stresa od suše ili hladnoće.",
    activeSubstance: "N 9% + B + Mn + Zn + Fe (helati)",
    dosage: "2–3 l/ha u 200–400 l vode",
    waiting: "3 dana",
    crops: ["Suncokret", "Soja", "Šećerna repa", "Povrće", "Voće"],
    features: ["Helatna forma mikroelemenata", "Visoka resorpcija kroz kutikulu", "Može se mešati sa pesticidima", "Brzo otklanja simptome deficijencije"],
    season: "Leto",
    relatedIds: [12, 14, 15]
  },
  {
    id: 14, emoji: "🌾", name: "Urea 46%", cat: "djubrivo",
    desc: "Azotno đubrivo za sve useve.",
    fullDesc: "Urea 46% N je visokokoncentrovano azotno đubrivo u granulisanom obliku sa 46% čistog azota. Najpopularnije azotno đubrivo na svetu, pogodno za prihranu u proleće i leto.",
    activeSubstance: "N 46%",
    dosage: "150–300 kg/ha",
    waiting: "—",
    crops: ["Pšenica", "Kukuruz", "Šećerna repa", "Livade i pašnjaci"],
    features: ["Najviši sadržaj azota od čvrstih đubriva", "Granulisana forma — lako se rasipa", "Brza apsorpcija kroz zemljište", "Dostupno u rasutom stanju"],
    season: "Proleće / Leto",
    relatedIds: [12, 13, 15]
  },
  {
    id: 15, emoji: "🧪", name: "Humus Plus", cat: "djubrivo",
    desc: "Organski poboljšivač strukture zemljišta.",
    fullDesc: "Humus Plus je organski meliorant koji sadrži huminske i fulvinske kiseline iz leonardita. Poboljšava strukturu tla, povećava kapacitet zadržavanja vode i stimuliše razvoj korenskog sistema.",
    activeSubstance: "Huminske kiseline 85%, Fulvinske kiseline 10%",
    dosage: "10–20 kg/ha (zajedno sa đubrivom)",
    waiting: "—",
    crops: ["Sve kulture", "Posebno za degradirana i peskovita tla"],
    features: ["Poboljšava strukturu i plodnost tla", "Povećava iskoristivost đubriva", "Stimuliše mikrobiološku aktivnost", "Smanjuje potrebu za mineralnim đubrivima"],
    season: "Sva godišnja doba",
    relatedIds: [12, 13, 20]
  },
  {
    id: 16, emoji: "🌰", name: "Pšenica Simonida", cat: "seme",
    desc: "Ozima sorta visokog prinosa.",
    fullDesc: "Simonida je ozima sorta pšenice domaće selekcije (NS Institut, Novi Sad) odlično prilagođena uslovima Vojvodine i šire. Odlikuje se visokim i stabilnim prinosom, kao i dobrom otpornošću na hladnoću.",
    activeSubstance: "Sertifikovano seme kategorije C1",
    dosage: "200–220 kg/ha (setva)",
    waiting: "—",
    crops: ["Ozima pšenica"],
    features: ["Prinos 7–9 t/ha u povoljnim uslovima", "Otporna na mraze i sušu", "Srednje rana sorta (klasa IV)", "Dobra otpornost na poleganje"],
    season: "Jesen (setva septembar–oktobar)",
    relatedIds: [1, 6, 17]
  },
  {
    id: 17, emoji: "🌽", name: "Hibrid Kukuruza PR37", cat: "seme", badge: "Novo",
    desc: "Visokoprinosni FAO 400 hibrid.",
    fullDesc: "PR37N01 je visokoprinosni hibrid kukuruza FAO grupe 400, razvijen za srednju Evropu i Balkan. Odlična genetska osnova za prinos zrna, sa izuzetnom tolerantnošću na stres od suše u kritičnim fazama.",
    activeSubstance: "Hibridno seme F1 kategorije",
    dosage: "70.000–75.000 biljaka/ha",
    waiting: "—",
    crops: ["Kukuruz"],
    features: ["Prinos 12–14 t/ha u optimalnim uslovima", "Tolerantan na sušni stres", "Dobra otpornost na lomljenje stabla", "Seme tretirano fungicidom i insekticidom"],
    season: "Proleće (setva april–maj)",
    relatedIds: [2, 10, 16]
  },
  {
    id: 18, emoji: "🌻", name: "Suncokret Partizan", cat: "seme",
    desc: "Domaća sorta sa visokim sadržajem ulja.",
    fullDesc: "Partizan je visokouljana sorta suncokreta domaće selekcije pogodna za intenzivnu i ekstenzivnu proizvodnju. Visok sadržaj ulja u semenu, dobra otpornost na sušu i najčešće bolesti.",
    activeSubstance: "Hibridno seme, IMI tolerantnost",
    dosage: "55.000–60.000 biljaka/ha",
    waiting: "—",
    crops: ["Suncokret"],
    features: ["Sadržaj ulja 46–48%", "Tolerantan na Orobanku rase E", "IMI — kompatibilan sa Express herbicidima", "Stabilan prinos u sušnim uslovima"],
    season: "Proleće (setva april)",
    relatedIds: [3, 5, 19]
  },
  {
    id: 19, emoji: "🌿", name: "Soja Vojvođanka", cat: "seme",
    desc: "Rana sorta za centralne i severne oblasti.",
    fullDesc: "Vojvođanka je rana sorta soje (00 grupa zrenja) prilagođena za Vojvodinu, Slavoniju i centralne delove Srbije. Uz pravilnu agrotehniku daje stabilne i visoke prinose, uz dobru otpornost na bolesti.",
    activeSubstance: "Sertifikovano seme kategorije C1",
    dosage: "80–100 kg/ha",
    waiting: "—",
    crops: ["Soja"],
    features: ["Grupa zrenja 00", "Prinos 3.5–4.5 t/ha", "Dobra nodulacija sa Rhizobiumom", "Pogodna za kasnu setvu"],
    season: "Proleće (setva april–maj)",
    relatedIds: [3, 18, 21]
  },
  {
    id: 20, emoji: "🔬", name: "Analiza Zemljišta", cat: "ostalo",
    desc: "Hemijska i fizička analiza parcele.",
    fullDesc: "Nudimo kompletnu agrohemijsku analizu zemljišta koja obuhvata određivanje pH vrednosti, sadržaja humusa, pristupačnog fosfora i kalijuma, kao i mikroelemenata. Na osnovu rezultata dobijate personalizovanu preporuku za đubrenje.",
    activeSubstance: "Usluga (laboratorijska analiza)",
    dosage: "Uzorkovanje na svakih 5 ha",
    waiting: "—",
    crops: ["Sve parcele"],
    features: ["pH, humus, P₂O₅, K₂O, mikroelementi", "Rezultati za 5–7 radnih dana", "Uz analizu dobijate preporuku za đubrenje", "Uzorkovanje po potrebi organizujemo sami"],
    season: "Jesen / Zima (optimalno)",
    relatedIds: [12, 15, 22]
  },
  {
    id: 21, emoji: "🪱", name: "Biostimulator Ruter", cat: "ostalo",
    desc: "Bolje ukorenjavanje sadnica.",
    fullDesc: "Ruter je tečni biostimulator na bazi IBA (indol-buterna kiselina) i vitamina B kompleksa. Stimuliše formiranje adventivnih korena kod reznica i sadnica, skraćuje vreme ukorenjivanja i poboljšava stopu preživljavanja.",
    activeSubstance: "IBA 2000 mg/l + vitamini B1, B6",
    dosage: "Potapanje osnove reznice: 5 ml/l vode (5 sek); zalivanje: 10–15 ml/l",
    waiting: "—",
    crops: ["Voćne sadnice", "Povrće", "Ukrasno bilje", "Lozni kalemovi"],
    features: ["Stimuliše razvoj korenskog sistema", "Poboljšava usvajanje vode i hraniva", "Prirodnog porekla — ne oštećuje biljku", "Može se primeniti folijarno i korenski"],
    season: "Proleće / Leto",
    relatedIds: [15, 13, 22]
  },
  {
    id: 22, emoji: "📋", name: "Plan Zaštite", cat: "ostalo",
    desc: "Godišnji plan tretmana za vaš usev.",
    fullDesc: "Naši agronomi izrađuju personalizovani godišnji plan zaštite bilja prilagođen vašim usevima, tipu zemljišta i istoriji problema na parceli. Plan uključuje preporuke preparata, doze, rokove primene i karence.",
    activeSubstance: "Agronomska usluga",
    dosage: "—",
    waiting: "—",
    crops: ["Po zahtevu — sve kulture"],
    features: ["Personalizovan za vaše gazdinstvo", "Uzima u obzir plodored i istoriju problema", "Usklađen sa zakonskim propisima", "Uz savetovanje tokom cele sezone"],
    season: "Zima / Proleće (planiranje)",
    relatedIds: [20, 21, 23]
  },
  {
    id: 23, emoji: "🧴", name: "Adjuvant Mix", cat: "ostalo",
    desc: "Poboljšivač efikasnosti škropiva.",
    fullDesc: "AdjuMix je nejonski surfaktant i okvašivač koji se dodaje u tank-mix sa pesticidima i folijarnim đubrivima. Smanjuje površinski napon kapljice, poboljšava rasprostiranje i penetraciju aktivnih supstanci u list.",
    activeSubstance: "Nejonski surfaktant 80% + okvašivač 15%",
    dosage: "0.05–0.1% (50–100 ml/100 l vode)",
    waiting: "—",
    crops: ["Kompatibilan sa svim kulturama"],
    features: ["Povećava efikasnost pesticida 15–25%", "Smanjuje gubitak od isparavanja", "Kompatibilan sa svim pesticidima", "Posebno koristan u suvim uslovima"],
    season: "Proleće / Leto",
    relatedIds: [5, 9, 22]
  },
];
